sudo: required
services:
  - docker #install docker

before_install:
  #Given by travis encrypt
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  #install google cloud sdk
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  #install kubectl
  - gcloud components update kubectl
  #give permission to deploy like an IAM role
  #create on gcp and download the json
  - gcloud auth activate-service-account --key-file service-account.json 

  #encrypt the downloaded file and encrypt it
  #docker run -it -v $(pwd):/app ruby:2.3 sh
  #gem install travis
  #travis encrypt-file service-account.json -r phirani27/multi-k8s




